# Generated by Django 4.2.16 on 2025-02-18 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('admin_delete', 'Deleted by Admin'), ('upload_failed', 'Upload Failed')], max_length=32)),
                ('hash_corpus_path', models.CharField(default=None, max_length=32, null=True)),
                ('real_corpus_path', models.CharField(default=None, max_length=100, null=True)),
                ('corpus_first_entry', models.TextField(default=None, max_length=1000, null=True)),
                ('pmids', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corpus',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('screening_status', models.CharField(choices=[('not_start', 'Not Start'), ('screening', 'Screening'), ('paused', 'Paused'), ('finished', 'Finished')], default='not_start', max_length=32)),
                ('current_screening_page', models.IntegerField(default=1, null=True)),
                ('show_docs_per_page', models.IntegerField(default=25)),
                ('pipeline_type', models.CharField(choices=[('pre-only', 'Pre-only'), ('pre-co', 'Pre-co'), ('co-only', 'Co-only'), ('pre-post', 'Pre-post'), ('co-post', 'Co-post'), ('post-only', 'Post-only'), ('full', 'Full')], default=None, max_length=32, null=True)),
                ('llm_interaction_level', models.BooleanField(default=None, null=True)),
                ('ranking_pages', models.JSONField(default=None, null=True)),
                ('ranking_method', models.CharField(choices=[('original', 'Original'), ('alphabetic', 'Alphabetic'), ('dense', 'Dense')], default='original', max_length=32)),
                ('page_screening_log', models.JSONField(default=None, null=True)),
                ('include_docs', models.JSONField(default=None, null=True)),
                ('exclude_docs', models.JSONField(default=None, null=True)),
                ('user_interactions', models.JSONField(default=None, null=True)),
                ('llm_parameters', models.JSONField(default=None, null=True)),
                ('co_ask_ai_prompt', models.JSONField(default=None, null=True)),
                ('started_screening_at', models.DateTimeField(default=None, null=True)),
                ('paused_screening_at', models.DateTimeField(default=None, null=True)),
                ('finished_screening_at', models.DateTimeField(default=None, null=True)),
                ('pos_at_waiting_queue', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(default=None, null=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.corpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='MasterPromptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('pre_prompt', 'Pre prompt'), ('co_ask_ai_prompt', 'Co ask AI prompt'), ('co_pico_extract_prompt', 'Co pico extract prompt'), ('co_detail_reason_prompt', 'Co detail reason prompt'), ('post_prompt', 'Post prompt')], default=None, max_length=32, null=True)),
                ('prompt_content', models.JSONField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_prompt_config',
            },
        ),
    ]
