# Generated by Django 4.2.16 on 2025-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ranking_pages',
            new_name='screening_pages',
        ),
        migrations.AddField(
            model_name='review',
            name='inclusion_criteria',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='masterpromptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('pre_prompt', 'Pre prompt'), ('co_ask_ai_prompt', 'Co ask AI prompt'), ('co_pico_extract_prompt', 'Co pico extract prompt'), ('co_detail_reason_prompt', 'Co detailed reasoning prompt'), ('post_prompt', 'Post prompt')], default=None, max_length=32, null=True),
        ),
    ]
