# Generated by Django 4.2.16 on 2025-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_change_aireview_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='structure_type',
            field=models.CharField(choices=[('page_based', 'Page-Based'), ('study_centric', 'Study-Centric')], default='study_centric', help_text='Format of the screening pages data structure', max_length=20),
        ),
    ]
