# Generated by Django 4.2.16 on 2025-03-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sorting_config',
            field=models.JSONField(default=dict, help_text='Additional sorting configuration parameters'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ranking_method',
            field=models.CharField(choices=[('original', 'Original'), ('alphabetic', 'Alphabetic'), ('dense', 'Dense'), ('custom', 'Custom Field')], default='original', max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='show_docs_per_page',
            field=models.IntegerField(default=5),
        ),
    ]
